-- Tenant-isolation / authorization tests. Run against a THROWAWAY local database only
-- (CI: supabase start). Seeds two schools, acts as real roles with JWT claims, and
-- verifies school A cannot see or change school B, and anon cannot reach money RPCs.
-- Failures are counted (not fatal one by one); the script fails at the end if any failed.
\set ON_ERROR_STOP on
select set_config('t.fail','0',false);
begin;
set local session_replication_role = replica;  -- seed without business triggers
insert into auth.users(id, aud, role, email) values
  ('aaaaaaaa-1111-0000-0000-00000000000a','authenticated','authenticated','owner.a@test.invalid'),
  ('bbbbbbbb-1111-0000-0000-00000000000b','authenticated','authenticated','owner.b@test.invalid'),
  ('aaaaaaaa-2222-0000-0000-00000000000a','authenticated','authenticated','parent.a@test.invalid'),
  ('aaaaaaaa-5555-0000-0000-00000000000a','authenticated','authenticated','parent.l@test.invalid');
insert into public.schools(id,name) values ('aaaaaaaa-0000-0000-0000-00000000000a','School A'),('bbbbbbbb-0000-0000-0000-00000000000b','School B');
insert into public.profiles(id,school_id,role,full_name) values
  ('aaaaaaaa-1111-0000-0000-00000000000a','aaaaaaaa-0000-0000-0000-00000000000a','owner','Owner A'),
  ('bbbbbbbb-1111-0000-0000-00000000000b','bbbbbbbb-0000-0000-0000-00000000000b','owner','Owner B'),
  ('aaaaaaaa-2222-0000-0000-00000000000a','aaaaaaaa-0000-0000-0000-00000000000a','parent','Parent A'),
  ('aaaaaaaa-5555-0000-0000-00000000000a','aaaaaaaa-0000-0000-0000-00000000000a','parent','Parent L');
insert into public.parent_students(school_id,parent_id,student_id) values ('aaaaaaaa-0000-0000-0000-00000000000a','aaaaaaaa-5555-0000-0000-00000000000a','aaaaaaaa-3333-0000-0000-00000000000a');
insert into public.employees(school_id,code,full_name,nationality) values ('aaaaaaaa-0000-0000-0000-00000000000a','EMP-A','Emp A','OM'),('bbbbbbbb-0000-0000-0000-00000000000b','EMP-B','Emp B','OM');
insert into public.students(id,school_id,code,full_name,grade) values
  ('aaaaaaaa-3333-0000-0000-00000000000a','aaaaaaaa-0000-0000-0000-00000000000a','STU-A1','Student A','الأول'),
  ('bbbbbbbb-3333-0000-0000-00000000000b','bbbbbbbb-0000-0000-0000-00000000000b','STU-B1','Student B','الأول');
insert into public.student_fees(id,school_id,student_id,description,total,paid) values
  ('aaaaaaaa-4444-0000-0000-00000000000a','aaaaaaaa-0000-0000-0000-00000000000a','aaaaaaaa-3333-0000-0000-00000000000a','fee A',100,0),
  ('bbbbbbbb-4444-0000-0000-00000000000b','bbbbbbbb-0000-0000-0000-00000000000b','bbbbbbbb-3333-0000-0000-00000000000b','fee B',100,0);
insert into public.accounts(id,school_id,code,name,type) values
  ('aaaaaaaa-7777-0000-0000-000000000001','aaaaaaaa-0000-0000-0000-00000000000a','1000','Cash A','asset'),('aaaaaaaa-7777-0000-0000-000000000002','aaaaaaaa-0000-0000-0000-00000000000a','4000','Revenue A','income');
insert into public.journal_entries(id,school_id) values ('aaaaaaaa-6666-0000-0000-00000000000a','aaaaaaaa-0000-0000-0000-00000000000a');
insert into public.journal_lines(school_id,entry_id,account_id,debit,credit) values
  ('aaaaaaaa-0000-0000-0000-00000000000a','aaaaaaaa-6666-0000-0000-00000000000a','aaaaaaaa-7777-0000-0000-000000000001',100,0),('aaaaaaaa-0000-0000-0000-00000000000a','aaaaaaaa-6666-0000-0000-00000000000a','aaaaaaaa-7777-0000-0000-000000000002',0,100);
commit;

-- Probe: what can a PARENT (profile in school A, no linked child) execute? Informational; never fails the run.
reset role;
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-2222-0000-0000-00000000000a","role":"authenticated"}',false);
set role authenticated;
create temp table probe_out(fn text, res text);
grant all on probe_out to authenticated;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.account_balances()) x$q$ into n, t; insert into probe_out values ('account_balances','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('account_balances','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.financial_summary()) x$q$ into n, t; insert into probe_out values ('financial_summary','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('financial_summary','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.cashflow_forecast()) x$q$ into n, t; insert into probe_out values ('cashflow_forecast','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('cashflow_forecast','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.collection_analytics()) x$q$ into n, t; insert into probe_out values ('collection_analytics','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('collection_analytics','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.dashboard_summary()) x$q$ into n, t; insert into probe_out values ('dashboard_summary','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('dashboard_summary','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.risk_scores()) x$q$ into n, t; insert into probe_out values ('risk_scores','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('risk_scores','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.org_overview()) x$q$ into n, t; insert into probe_out values ('org_overview','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('org_overview','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.overdue_reminders()) x$q$ into n, t; insert into probe_out values ('overdue_reminders','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('overdue_reminders','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.payroll_yearly_summary(2026)) x$q$ into n, t; insert into probe_out values ('payroll_yearly_summary','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('payroll_yearly_summary','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.meal_suppliers()) x$q$ into n, t; insert into probe_out values ('meal_suppliers','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('meal_suppliers','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.inventory_purchases_summary()) x$q$ into n, t; insert into probe_out values ('inventory_purchases_summary','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('inventory_purchases_summary','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.inventory_category_report()) x$q$ into n, t; insert into probe_out values ('inventory_category_report','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('inventory_category_report','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.food_inventory_list()) x$q$ into n, t; insert into probe_out values ('food_inventory_list','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('food_inventory_list','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.my_school_feedback()) x$q$ into n, t; insert into probe_out values ('my_school_feedback','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('my_school_feedback','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.intelligence_status()) x$q$ into n, t; insert into probe_out values ('intelligence_status','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('intelligence_status','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.copilot_gated()) x$q$ into n, t; insert into probe_out values ('copilot_gated','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('copilot_gated','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.grade_fees_list()) x$q$ into n, t; insert into probe_out values ('grade_fees_list','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('grade_fees_list','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.my_financial_years()) x$q$ into n, t; insert into probe_out values ('my_financial_years','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('my_financial_years','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.my_vat_setting()) x$q$ into n, t; insert into probe_out values ('my_vat_setting','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('my_vat_setting','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.inventory_categories()) x$q$ into n, t; insert into probe_out values ('inventory_categories','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('inventory_categories','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.plan_usage()) x$q$ into n, t; insert into probe_out values ('plan_usage','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('plan_usage','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.my_subscription_status()) x$q$ into n, t; insert into probe_out values ('my_subscription_status','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('my_subscription_status','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.available_plans()) x$q$ into n, t; insert into probe_out values ('available_plans','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('available_plans','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.current_academic_year()) x$q$ into n, t; insert into probe_out values ('current_academic_year','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('current_academic_year','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.school_pricing_complete()) x$q$ into n, t; insert into probe_out values ('school_pricing_complete','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('school_pricing_complete','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.balance_sheet_asof(current_date)) x$q$ into n, t; insert into probe_out values ('balance_sheet_asof','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('balance_sheet_asof','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.income_statement_period(current_date-30,current_date)) x$q$ into n, t; insert into probe_out values ('income_statement_period','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('income_statement_period','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.journal_period(current_date-30,current_date)) x$q$ into n, t; insert into probe_out values ('journal_period','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('journal_period','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.trial_balance_period(current_date-30,current_date)) x$q$ into n, t; insert into probe_out values ('trial_balance_period','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('trial_balance_period','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.vat_report_period(current_date-30,current_date)) x$q$ into n, t; insert into probe_out values ('vat_report_period','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('vat_report_period','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.meal_cost_report('month')) x$q$ into n, t; insert into probe_out values ('meal_cost_report','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('meal_cost_report','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.meal_purchases_list('month')) x$q$ into n, t; insert into probe_out values ('meal_purchases_list','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('meal_purchases_list','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.inventory_list(null)) x$q$ into n, t; insert into probe_out values ('inventory_list','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('inventory_list','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.inventory_dispenses_list(10)) x$q$ into n, t; insert into probe_out values ('inventory_dispenses_list','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('inventory_dispenses_list','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.student_parents('aaaaaaaa-3333-0000-0000-00000000000a'::uuid)) x$q$ into n, t; insert into probe_out values ('student_parents','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('student_parents','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.student_certificates('aaaaaaaa-3333-0000-0000-00000000000a'::uuid)) x$q$ into n, t; insert into probe_out values ('student_certificates','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('student_certificates','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.validate_wps_run('cccccccc-0000-0000-0000-000000000001'::uuid)) x$q$ into n, t; insert into probe_out values ('validate_wps_run','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('validate_wps_run','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.cancel_pending_payment('cccccccc-0000-0000-0000-000000000001'::uuid)) x$q$ into n, t; insert into probe_out values ('cancel_pending_payment','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('cancel_pending_payment','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.calc_social_insurance(500,0,'OM')) x$q$ into n, t; insert into probe_out values ('calc_social_insurance','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('calc_social_insurance','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.claim_queue_batch(5)) x$q$ into n, t; insert into probe_out values ('claim_queue_batch','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('claim_queue_batch','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.mark_queue_result('cccccccc-0000-0000-0000-000000000001'::uuid,true,null,null)) x$q$ into n, t; insert into probe_out values ('mark_queue_result','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('mark_queue_result','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.cleanup_rate_limits()) x$q$ into n, t; insert into probe_out values ('cleanup_rate_limits','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('cleanup_rate_limits','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.check_rate_limit('k',5,60)) x$q$ into n, t; insert into probe_out values ('check_rate_limit','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('check_rate_limit','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.check_and_increment_rate_limit('k',5,1)) x$q$ into n, t; insert into probe_out values ('check_and_increment_rate_limit','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('check_and_increment_rate_limit','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.next_invoice_number('bbbbbbbb-0000-0000-0000-00000000000b'::uuid)) x$q$ into n, t; insert into probe_out values ('next_invoice_number','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('next_invoice_number','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.next_expense_code('bbbbbbbb-0000-0000-0000-00000000000b'::uuid)) x$q$ into n, t; insert into probe_out values ('next_expense_code','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('next_expense_code','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.ensure_cafeteria_account()) x$q$ into n, t; insert into probe_out values ('ensure_cafeteria_account','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('ensure_cafeteria_account','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.ensure_inventory_accounts()) x$q$ into n, t; insert into probe_out values ('ensure_inventory_accounts','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('ensure_inventory_accounts','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.ensure_meal_cost_accounts()) x$q$ into n, t; insert into probe_out values ('ensure_meal_cost_accounts','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('ensure_meal_cost_accounts','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.ensure_transport_account()) x$q$ into n, t; insert into probe_out values ('ensure_transport_account','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('ensure_transport_account','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.mark_notifications_read()) x$q$ into n, t; insert into probe_out values ('mark_notifications_read','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('mark_notifications_read','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.accept_staff_invite()) x$q$ into n, t; insert into probe_out values ('accept_staff_invite','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('accept_staff_invite','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.switch_active_school('bbbbbbbb-0000-0000-0000-00000000000b'::uuid)) x$q$ into n, t; insert into probe_out values ('switch_active_school','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('switch_active_school','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.start_impersonation('bbbbbbbb-0000-0000-0000-00000000000b'::uuid,'x')) x$q$ into n, t; insert into probe_out values ('start_impersonation','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('start_impersonation','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.my_schools()) x$q$ into n, t; insert into probe_out values ('my_schools','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('my_schools','err: '||left(sqlerrm,40)); end; end $$;
do $$ declare n int; t text; begin begin execute $q$select count(*), left(string_agg(x::text,'|'),40) from (select * from public.student_payment_tracker('aaaaaaaa-3333-0000-0000-00000000000a'::uuid)) x$q$ into n, t; insert into probe_out values ('student_payment_tracker','OK rows='||n||' '||coalesce(t,'')); exception when others then insert into probe_out values ('student_payment_tracker','err: '||left(sqlerrm,40)); end; end $$;
reset role;
select 'PROBE ' || string_agg(fn||' => '||res, ' ; ' order by fn) from probe_out where res like 'OK%';
