-- RusoomPay — Baseline 1/6: الامتدادات والأنواع والجداول
-- مولَّد حرفياً من كتالوج قاعدة الإنتاج (hmskpglpltaeiznvxvcb).
-- يجب أن يبقى أقدم migration في المجلد ليُنفَّذ أولاً.

create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists pgcrypto with schema extensions;

CREATE TYPE public.req_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE public.student_status AS ENUM ('active', 'transferred', 'graduated');
CREATE TYPE public.sub_plan AS ENUM ('trial', 'monthly', 'yearly', 'lifetime', 'starter', 'small', 'basic', 'advanced', 'enterprise');
CREATE TYPE public.sub_status AS ENUM ('trial', 'active', 'pending', 'expired');
CREATE TYPE public.user_role AS ENUM ('owner', 'admin', 'accountant', 'parent', 'student', 'platform_admin');

CREATE TABLE public.academic_years (id uuid NOT NULL DEFAULT gen_random_uuid(), school_id uuid NOT NULL, label text NOT NULL, start_date date NOT NULL, end_date date NOT NULL, is_current boolean NOT NULL DEFAULT false, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.accounts (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, code text NOT NULL, name text NOT NULL, type text NOT NULL, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.announcements (id uuid NOT NULL DEFAULT uuid_generate_v4(), title text NOT NULL, body text NOT NULL, kind text NOT NULL DEFAULT 'info'::text, target text NOT NULL DEFAULT 'all'::text, created_by uuid, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.assistant_conversations (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, user_id uuid NOT NULL, title text, created_at timestamp with time zone NOT NULL DEFAULT now(), updated_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.assistant_messages (id uuid NOT NULL DEFAULT uuid_generate_v4(), conversation_id uuid NOT NULL, school_id uuid NOT NULL, role text NOT NULL, content text NOT NULL, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.audit_log (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, actor_id uuid, action text NOT NULL, details text, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.backup_log (school_id uuid NOT NULL, last_backup timestamp with time zone NOT NULL DEFAULT now(), actor_id uuid, count integer NOT NULL DEFAULT 1);
CREATE TABLE public.bus_subscriptions (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, student_id uuid NOT NULL, bus_id uuid NOT NULL, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.buses (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, route text NOT NULL, driver text NOT NULL, capacity integer NOT NULL DEFAULT 30, fee numeric(12,3) NOT NULL DEFAULT 0, pay_to text NOT NULL DEFAULT 'school'::text, created_at timestamp with time zone NOT NULL DEFAULT now(), supervisor text, routes text[] NOT NULL DEFAULT '{}'::text[]);
CREATE TABLE public.cafeteria_billing (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, month text NOT NULL, billed_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.certificate_requests (id uuid NOT NULL DEFAULT gen_random_uuid(), school_id uuid NOT NULL, student_id uuid NOT NULL, parent_id uuid NOT NULL, kind text NOT NULL DEFAULT 'enrollment'::text, status text NOT NULL DEFAULT 'pending'::text, certificate_id uuid, reason text, reviewed_by uuid, reviewed_at timestamp with time zone, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.certificates (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, student_id uuid NOT NULL, kind text NOT NULL, title text NOT NULL, serial text NOT NULL, body text, file_path text, file_name text, issued_by uuid, created_at timestamp with time zone NOT NULL DEFAULT now(), deleted_at timestamp with time zone);
CREATE TABLE public.employees (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, code text NOT NULL, full_name text NOT NULL, job_title text, nationality text NOT NULL DEFAULT 'om'::text, iban text, created_at timestamp with time zone NOT NULL DEFAULT now(), deleted_at timestamp with time zone, manager_id uuid, photo_url text, email text, id_type text DEFAULT 'CIVIL'::text, id_number text, bank_name text, bank_account_no text, basic_salary numeric(12,3) NOT NULL DEFAULT 0, housing_allowance numeric(12,3) NOT NULL DEFAULT 0, transport_allowance numeric(12,3) NOT NULL DEFAULT 0, other_allowance numeric(12,3) NOT NULL DEFAULT 0, subject_to_pasi boolean NOT NULL DEFAULT true, pasi_exemption_reason text, basic numeric DEFAULT basic_salary, allowance numeric DEFAULT ((housing_allowance + transport_allowance) + other_allowance), department text DEFAULT 'teaching'::text, org_level integer NOT NULL DEFAULT 3);
CREATE TABLE public.error_log (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid, source text NOT NULL, severity text NOT NULL DEFAULT 'error'::text, message text NOT NULL, context jsonb, request_id text, resolved boolean NOT NULL DEFAULT false, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.feedback (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, author_id uuid, author_name text, kind text NOT NULL DEFAULT 'complaint'::text, priority text NOT NULL DEFAULT 'normal'::text, body text NOT NULL, status text NOT NULL DEFAULT 'open'::text, reply text, created_at timestamp with time zone NOT NULL DEFAULT now(), updated_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.food_dispenses (id uuid NOT NULL DEFAULT gen_random_uuid(), school_id uuid NOT NULL, item_id uuid NOT NULL, qty numeric NOT NULL, cost numeric NOT NULL DEFAULT 0, reason text, dispensed_by uuid, dispensed_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.food_inventory (id uuid NOT NULL DEFAULT gen_random_uuid(), school_id uuid NOT NULL, name text NOT NULL, unit text NOT NULL DEFAULT 'كجم'::text, qty numeric NOT NULL DEFAULT 0, cost numeric NOT NULL DEFAULT 0, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.grade_fees (id uuid NOT NULL DEFAULT gen_random_uuid(), school_id uuid NOT NULL, grade text NOT NULL, annual_fee numeric NOT NULL DEFAULT 0, created_at timestamp with time zone NOT NULL DEFAULT now(), updated_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.guardian_invites (id uuid NOT NULL DEFAULT gen_random_uuid(), school_id uuid NOT NULL, phone text NOT NULL, invited_at timestamp with time zone NOT NULL DEFAULT now(), invited_by uuid);
CREATE TABLE public.help_articles (id uuid NOT NULL DEFAULT uuid_generate_v4(), slug text NOT NULL, category text NOT NULL, page_route text, title text NOT NULL, summary text NOT NULL, body text NOT NULL, steps jsonb NOT NULL DEFAULT '[]'::jsonb, media jsonb NOT NULL DEFAULT '[]'::jsonb, keywords text[] NOT NULL DEFAULT '{}'::text[], role_scope text[] NOT NULL DEFAULT '{}'::text[], sort_order integer NOT NULL DEFAULT 100, is_published boolean NOT NULL DEFAULT true, created_at timestamp with time zone NOT NULL DEFAULT now(), updated_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.intelligence_flags (school_id uuid NOT NULL, engine text NOT NULL, enabled boolean NOT NULL DEFAULT true, updated_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.inventory_dispenses (id uuid NOT NULL DEFAULT gen_random_uuid(), school_id uuid NOT NULL, item_id uuid NOT NULL, qty integer NOT NULL, cost numeric NOT NULL DEFAULT 0, reason text, dispensed_by uuid, dispensed_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.inventory_items (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, name text NOT NULL, qty integer NOT NULL DEFAULT 0, cost numeric(12,3) NOT NULL DEFAULT 0, price numeric(12,3) NOT NULL DEFAULT 0, vat_rate numeric(4,2) NOT NULL DEFAULT 5, created_at timestamp with time zone NOT NULL DEFAULT now(), category text NOT NULL DEFAULT 'أخرى'::text, subtype text);
CREATE TABLE public.journal_entries (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, entry_date date NOT NULL DEFAULT CURRENT_DATE, description text, reference text, created_by uuid, created_at timestamp with time zone NOT NULL DEFAULT now(), deleted_at timestamp with time zone, fee_id uuid, reversed_by_entry uuid, reverses_entry uuid, is_locked boolean NOT NULL DEFAULT true);
CREATE TABLE public.journal_lines (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, entry_id uuid NOT NULL, account_id uuid NOT NULL, debit numeric(12,3) NOT NULL DEFAULT 0, credit numeric(12,3) NOT NULL DEFAULT 0);
CREATE TABLE public.legal_consents (id uuid NOT NULL DEFAULT gen_random_uuid(), user_id uuid NOT NULL, school_id uuid, document_type text NOT NULL, version text NOT NULL, accepted_at timestamp with time zone NOT NULL DEFAULT now(), ip_address inet, user_agent text);
CREATE TABLE public.meal_orders (id uuid NOT NULL DEFAULT gen_random_uuid(), school_id uuid NOT NULL, student_id uuid NOT NULL, plan_id uuid NOT NULL, meal_date date NOT NULL, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.meal_plans (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, name text NOT NULL, fee numeric(12,3) NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true, created_at timestamp with time zone NOT NULL DEFAULT now(), plan_type text NOT NULL DEFAULT 'monthly'::text);
CREATE TABLE public.meal_purchases (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, supplier_id uuid, purchase_date date NOT NULL DEFAULT CURRENT_DATE, purchase_type text NOT NULL DEFAULT 'daily'::text, meals_count integer NOT NULL DEFAULT 0, unit_cost numeric(12,3) NOT NULL DEFAULT 0, total_cost numeric(12,3) NOT NULL DEFAULT 0, period text, paid boolean NOT NULL DEFAULT false, notes text, created_by uuid, created_at timestamp with time zone NOT NULL DEFAULT now(), updated_at timestamp with time zone NOT NULL DEFAULT now(), journal_entry_id uuid);
CREATE TABLE public.meal_subscriptions (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, student_id uuid NOT NULL, plan_id uuid NOT NULL, created_at timestamp with time zone NOT NULL DEFAULT now(), billing text NOT NULL DEFAULT 'monthly'::text, last_billed_month text, billing_method text DEFAULT 'separate'::text);
CREATE TABLE public.notification_queue (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, channel text NOT NULL, recipient text NOT NULL, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'queued'::text, attempts integer NOT NULL DEFAULT 0, max_attempts integer NOT NULL DEFAULT 5, next_retry_at timestamp with time zone NOT NULL DEFAULT now(), last_error text, provider_id text, dedupe_key text, created_at timestamp with time zone NOT NULL DEFAULT now(), sent_at timestamp with time zone);
CREATE TABLE public.notifications (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, audience text NOT NULL, guardian_id uuid, body text NOT NULL, is_read boolean NOT NULL DEFAULT false, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.parent_students (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, parent_id uuid NOT NULL, student_id uuid NOT NULL, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.payment_state_log (id uuid NOT NULL DEFAULT uuid_generate_v4(), payment_id uuid NOT NULL, school_id uuid NOT NULL, from_state text, to_state text NOT NULL, reason text, actor_id uuid, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.payments (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, fee_id uuid NOT NULL, amount numeric(12,3) NOT NULL, method text NOT NULL DEFAULT 'bank'::text, paid_at date NOT NULL DEFAULT CURRENT_DATE, recorded_by uuid, created_at timestamp with time zone NOT NULL DEFAULT now(), deleted_at timestamp with time zone);
CREATE TABLE public.payroll_items (id uuid NOT NULL DEFAULT gen_random_uuid(), run_id uuid NOT NULL, employee_id uuid NOT NULL, employee_name text NOT NULL, id_type text, id_number text, bank_name text, bank_account_no text, working_days integer NOT NULL DEFAULT 30, basic_salary numeric(12,3) NOT NULL DEFAULT 0, extra_income numeric(12,3) NOT NULL DEFAULT 0, deductions numeric(12,3) NOT NULL DEFAULT 0, pasi_employee numeric(12,3) NOT NULL DEFAULT 0, pasi_employer numeric(12,3) NOT NULL DEFAULT 0, net_salary numeric(12,3) DEFAULT (((basic_salary + extra_income) - deductions) - pasi_employee), created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.payroll_runs (id uuid NOT NULL DEFAULT gen_random_uuid(), school_id uuid NOT NULL, period_year integer NOT NULL, period_month integer NOT NULL, value_date date, status text NOT NULL DEFAULT 'draft'::text, total_gross numeric(14,3) NOT NULL DEFAULT 0, total_deduct numeric(14,3) NOT NULL DEFAULT 0, total_net numeric(14,3) NOT NULL DEFAULT 0, total_pasi_er numeric(14,3) NOT NULL DEFAULT 0, journal_entry_id uuid, created_by uuid, approved_at timestamp with time zone, created_at timestamp with time zone NOT NULL DEFAULT now(), payment_journal_entry_id uuid);
CREATE TABLE public.payroll_settings (school_id uuid NOT NULL, employer_cr_no text, payer_cr_no text, wps_email text, wps_phone text, debit_account_no text, bank_name text, updated_at timestamp with time zone NOT NULL DEFAULT now(), wps_bank_profile text DEFAULT 'BANK_MUSCAT'::text);
CREATE TABLE public.pending_payments (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, fee_id uuid NOT NULL, guardian_id uuid, amount numeric(12,3) NOT NULL, method text NOT NULL DEFAULT 'card'::text, bank_ref text, status text NOT NULL DEFAULT 'pending'::text, created_at timestamp with time zone NOT NULL DEFAULT now(), resolved_at timestamp with time zone, resolved_by uuid, txn_state text NOT NULL DEFAULT 'pending'::text, provider_ref text, idempotency_key text, state_updated_at timestamp with time zone NOT NULL DEFAULT now(), failure_reason text, receipt_url text);
CREATE TABLE public.plans (code text NOT NULL, name_ar text NOT NULL, price_omr numeric NOT NULL, price_regular numeric, offer_ends_at date, max_students integer, max_staff integer, max_branches integer, sort_order integer NOT NULL, is_active boolean DEFAULT true);
CREATE TABLE public.platform_countries (code text NOT NULL, name_ar text NOT NULL, currency text NOT NULL, enabled boolean NOT NULL DEFAULT false, updated_at timestamp with time zone NOT NULL DEFAULT now(), vat_rate numeric(5,2) NOT NULL DEFAULT 0, vat_mode text NOT NULL DEFAULT 'none'::text);
CREATE TABLE public.profiles (id uuid NOT NULL, school_id uuid, role user_role NOT NULL DEFAULT 'admin'::user_role, full_name text NOT NULL, phone text, active boolean NOT NULL DEFAULT true, created_at timestamp with time zone NOT NULL DEFAULT now(), impersonation_reason text, impersonating_school_id uuid);
CREATE TABLE public.promotion_log (id uuid NOT NULL DEFAULT gen_random_uuid(), school_id uuid NOT NULL, actor_id uuid NOT NULL, academic_year text NOT NULL, promoted integer NOT NULL DEFAULT 0, repeated integer NOT NULL DEFAULT 0, graduated integer NOT NULL DEFAULT 0, created_at timestamp with time zone DEFAULT now());
CREATE TABLE public.rate_limits (key text NOT NULL, count integer NOT NULL DEFAULT 0, window_start timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.receipt_verifications (id uuid NOT NULL DEFAULT gen_random_uuid(), school_registration_id uuid, reference_number text, amount_extracted numeric, recipient_extracted text, date_extracted date, verification_status text, verification_reason text, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.recommendation_log (id uuid NOT NULL DEFAULT gen_random_uuid(), school_id uuid NOT NULL, actor_id uuid NOT NULL, rec_type text NOT NULL, rec_title text NOT NULL, target_count integer, expected_amount numeric, actual_amount numeric DEFAULT 0, status text DEFAULT 'acted'::text, created_at timestamp with time zone DEFAULT now(), measured_at timestamp with time zone);
CREATE TABLE public.salary_requests (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, employee_id uuid NOT NULL, old_basic numeric(12,3), old_allow numeric(12,3), new_basic numeric(12,3), new_allow numeric(12,3), requested_by uuid, decided_by uuid, status req_status NOT NULL DEFAULT 'pending'::req_status, created_at timestamp with time zone NOT NULL DEFAULT now(), decided_at timestamp with time zone);
CREATE TABLE public.school_registrations (id uuid NOT NULL DEFAULT gen_random_uuid(), school_name text NOT NULL, contact_name text NOT NULL, phone text NOT NULL, email text, city text, plan text NOT NULL, status text NOT NULL DEFAULT 'pending'::text, notes text, created_at timestamp with time zone NOT NULL DEFAULT now(), updated_at timestamp with time zone NOT NULL DEFAULT now(), verification_status text, verification_reason text);
CREATE TABLE public.schools (id uuid NOT NULL DEFAULT uuid_generate_v4(), name text NOT NULL, branch text, country text NOT NULL DEFAULT 'OM'::text, currency text NOT NULL DEFAULT 'OMR'::text, governorate text, cr_number text, moe_license text, vat_number text, phone text, email text, address text, logo_url text, color text DEFAULT '#0F2744'::text, created_at timestamp with time zone NOT NULL DEFAULT now(), bank_name text, bank_account text, bank_iban text, bank_holder text, bank_enabled boolean NOT NULL DEFAULT false, ins_emp_rate numeric(6,4) NOT NULL DEFAULT 0.08, ins_er_rate numeric(6,4) NOT NULL DEFAULT 0.125, ins_cap numeric(12,3), ins_expat_exempt boolean NOT NULL DEFAULT true, ins_configured boolean NOT NULL DEFAULT false, vat_enabled boolean NOT NULL DEFAULT false, active boolean NOT NULL DEFAULT true, section_styles text[] NOT NULL DEFAULT '{ar_letters}'::text[], is_test boolean NOT NULL DEFAULT false, card_accent_color text DEFAULT '#B08D2E'::text);
CREATE TABLE public.staff_invites (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, email text NOT NULL, role user_role NOT NULL, full_name text, status text NOT NULL DEFAULT 'pending'::text, invited_by uuid, created_at timestamp with time zone NOT NULL DEFAULT now(), accepted_at timestamp with time zone);
CREATE TABLE public.student_fees (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, student_id uuid NOT NULL, description text NOT NULL, total numeric(12,3) NOT NULL DEFAULT 0, paid numeric(12,3) NOT NULL DEFAULT 0, due_date date, created_at timestamp with time zone NOT NULL DEFAULT now(), deleted_at timestamp with time zone, revenue_account_code text NOT NULL DEFAULT '4100'::text, academic_year_id uuid);
CREATE TABLE public.students (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, code text NOT NULL, full_name text NOT NULL, grade text NOT NULL, section text, guardian_name text, guardian_phone text, status student_status NOT NULL DEFAULT 'active'::student_status, repeater boolean NOT NULL DEFAULT false, promoted_year integer, attendance numeric(5,2) DEFAULT 100, joined_at date DEFAULT CURRENT_DATE, created_at timestamp with time zone NOT NULL DEFAULT now(), deleted_at timestamp with time zone, guardian_email text, birth_date date, gender text, annual_fee numeric(12,3) DEFAULT 0, transport_type text DEFAULT 'none'::text, father_phone text, mother_phone text, address text, discount_pct numeric NOT NULL DEFAULT 0);
CREATE TABLE public.subscriptions (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, plan sub_plan NOT NULL DEFAULT 'trial'::sub_plan, status sub_status NOT NULL DEFAULT 'trial'::sub_status, trial_ends_at timestamp with time zone, renews_at timestamp with time zone, pay_method text, receipt_url text, created_at timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE public.suppliers (id uuid NOT NULL DEFAULT uuid_generate_v4(), school_id uuid NOT NULL, name text NOT NULL, contact_name text, phone text, email text, vat_number text, active boolean NOT NULL DEFAULT true, created_at timestamp with time zone NOT NULL DEFAULT now());
